[build]
  publish = "build/client"
  command = "npm run build"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
