[build]
command = "remix vite:build"
publish = "public"
 
[dev]
command = "remix vite:dev"
port = 5173
framework = "remix"
 
# Set immutable caching for static files, because they have fingerprinted filenames
 
[[headers]]
for = "/build/*"
 
[headers.values]
 
"Cache-Control" = "public, max-age=31560000, immutable"
